spring:
  datasource:
    url: jdbc:mysql://localhost/dinner
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

server:
  servlet:
    context-path: /dinner